geofield_311.settings:
  type: config_object
  label: 'Geofield 311 settings'
  mapping:
    geojson_app_limit:
      type: mapping
      label: 'Geojson App Limit Settings'
      mapping:
        markers_location:
          type: mapping
          label: 'Markers Icons Storage location Info'
          mapping:
            file:
              type: string
              label: 'Geojson file location'
