# Schema for the views plugins of the italo_module module.

views.filter_value.date_range_active_status_filter:
  type: mapping
  label: 'Active status'
  mapping:
    state:
      type: string
      label: 'Active status'

